### ISSUE TITLE
Fix maybeStripTime error

### ISSUE THREAD

**Issue by acaldas** [powerhouse-inc/design-system#208]
Strings with a number and a `T` in the name were being altered, for example `'Test Asset 2' => ''`

Also, making changes through the Storybook UI throws an exception due to Storybook passing a date as Date instead of string.

![Image](https://github.com/powerhouse-inc/design-system/assets/5501872/cab80c9e-c13d-49bd-8d53-05a2eb43e690)

**Comment by ryanwolhuter** [comment]
This is happening because of the problematic date picker library that we are using in the ui. It forces us to convert between their proprietary `CalendarDate` type which cannot have time information. But zod's datetime needs the time information or else the parsing fails.

To solve this properly we need to use something else for inputting dates, especially because this library only allows inputting dates and not times. We need to allow time information for most of our timestamp inputs
